### PR TITLE
Fix for expiration_window, adds validation in certificate resource cr…

### LINKED ISSUE #79: Setting an Expiration Window can block Terraform from destroying resources
**PROBLEM SUMMARY**
If you request a certificate with an expiration window greater than the Issuing Templates validity period you will be be unable to destroy the terraform resources during clean up. 

**STEPS TO REPRODUCE**
- Create an Issuing Template within VaaS with a validity period of 168 hours. 
- Create a certificate request using the provider with an expiration window greater than 168. I'll use 720 in this example. 
- Run `terraform apply`. This will issue the certificate successfully.
- Run `terraform destroy`. This will throw an error and not delete any resources.
`Error: certificate validity duration 168h0m30s is less than configured expiration window 720h0m0s`

**EXPECTED RESULTS**
The certificate resource within Terraform should be destroyed OR the request shouldn't have occurred in the first place.

**ACTUAL RESULTS**
```
resource "venafi_certificate" "tls_server" {
  common_name = "web.venafi.example"
  san_dns = [
    "web01.venafi.example",
    "web02.venafi.example"
  ]
  algorithm = "RSA"
  rsa_bits = 2048
  expiration_window = 720
}
```
`Error: certificate validity duration 168h0m30s is less than configured expiration window 720h0m0s`

**ENVIRONMENT DETAILS**
VaaS
Venafi Terraform Provider version 0.13

**COMMENTS/WORKAROUNDS**
Either allow the certificate to be destroyed or block the initial creation of the certificate if the `expiration_window` is greater than the Issuing Template validity policy.

### PR DESCRIPTION
**Pull request by luispresuelVenafi**
Closes: https://github.com/Venafi/terraform-provider-venafi/issues/79 and https://github.com/Venafi/terraform-provider-venafi/issues/82

Fix for expiration_window: adds validation in certificate resource creation and update. Refactors function in order to only call a log as a warning we setting a greater expiration_window than the cert validity. Adds refactoring for tests as well as more tests accordingly

### CODE REVIEW

File: venafi/resource_venafi_certificate.go [hunk 1]
```diff
@@ -197,7 +197,19 @@ func resourceVenafiCertificateCreate(d *schema.ResourceData, meta interface{}) e
 func resourceVenafiCertificateUpdate(d *schema.ResourceData, meta interface{}) error {
 	if d.HasChange("expiration_window") {
 		expiration_window := d.Get("expiration_window").(int)
-		err := d.Set("expiration_window", expiration_window)
+		certUntyped, ok := d.GetOk("certificate")
```
Comment (marcos-albornoz) [inline venafi/resource_venafi_certificate.go:202]: I think that block of code should be extracted to another function

File: venafi/resource_venafi_certificate.go [hunk 2]
```diff
@@ -260,14 +269,24 @@ func resourceVenafiCertificateExists(d *schema.ResourceData, meta interface{}) (
 	return true, nil
 }
 
-func checkForRenew(cert x509.Certificate, expirationWindow int) (renewRequired bool, err error) {
+// expirationWindowAboveValidityPeriod as the name says is the expiration_window is greater than the  validity_period
+// return a bool and the current duration of the certificate
+// expects x509.Certificate and the expiration_window in time.Duration converted to hours
+func expirationWindowAboveValidityPeriod(cert *x509.Certificate, renewWindowHours time.Duration) (boolean bool, duration *int64) {
```
Comment (marcos-albornoz) [inline venafi/resource_venafi_certificate.go]: Rename the function

File: venafi/resource_venafi_certificate.go [hunk 3]
```diff
@@ -260,14 +269,24 @@ func resourceVenafiCertificateExists(d *schema.ResourceData, meta interface{}) (
...
+	currentDuration := cert.NotAfter.Sub(cert.NotBefore)
```
Comment (marcos-albornoz) [inline venafi/resource_venafi_certificate.go:287]: Please extract this line of code in another function

**Review by ricrodriguezg — APPROVED** [review]

**Review by marcos-albornoz — APPROVED** [review]
