### PR TITLE
Enhancement/exposes object name

### LINKED ISSUE #94: "Error comparing certificate and key" when creating more than one certificate resource for the same hostname
**PROBLEM SUMMARY**
When I try to create multiple certificates using the same hostname, the private keys are generated incorrectly and `terraform plan` starts failing every run until the Terraform state file is manually repaired.

**STEPS TO REPRODUCE**
`terraform apply` where the "for each" spawns 3 counts of `auth_cert`

```
resource "venafi_certificate" "auth_cert" {
  for_each = {
    for name, spn in local.spn_to_create : name => spn
    if spn.certificate
  }
  common_name = "test-subdomain.subdomain.domain.net"
  algorithm   = "RSA"
  rsa_bits    = "2048"
}
```

**EXPECTED RESULTS**
I get 3 valid certificates resources and no issues.

**ACTUAL RESULTS**

- the first certificate resource has correct certificate and private key fields
- the second certificate resource has the same certificate as the first one, but a different private key which doesn't match the certificate
- the third certificate resource has the same certificate as the first one, but a different private key which doesn't match the certificate

The private key and the certificate are compared to each other during each `terraform plan/apply/destroy` run, and this mismatch is detected here:
https://github.com/Venafi/terraform-provider-venafi/blob/master/venafi/resource_venafi_certificate.go#L323
throwing this error message, and failing the run:
```
error comparing certificate and key: tls: failed to find any PEM data in key input
```
This is particularly nasty, because it locks you out of most standard Terraform commands. 

**ENVIRONMENT DETAILS**
- terraform-provider-venafi v0.16.0
- Terraform v1.1.7

**COMMENTS/WORKAROUNDS**
The only recovery is to remove the offending certificate resources from the Terraform state.

Thanks to @samuelstolicny @miroslavkohutik for finding and diagnosing the bug.

### PR DESCRIPTION
**Pull request by luispresuelVenafi**
Closes https://github.com/Venafi/terraform-provider-venafi/issues/94

We expose "nickname" when requesting a certificate so we have the ability to explicitly set object name of the certificate at TPP, which overrides the default behavior of using the common_name as the object name.

It also includes:
- Bug fix: We refactor verification function for certificate key-pair and also add it in certificate resource creation.
- Starts work for setting constants for our provider resource in order to make it less error prone

### CODE REVIEW

File: venafi/resource_venafi_certificate.go [hunk 1]
```diff
@@ -60,6 +60,12 @@ func resourceVenafiCertificate() *schema.Resource {
 				Description: "Common name of certificate",
 				ForceNew:    true,
 			},
+			"object_name": &schema.Schema{
```
Comment (tr1ck3r) [inline venafi/resource_venafi_certificate.go]: I think we should call this `nickname` to be consistent with [TPP (Aperture)](https://docs.venafi.com/Docs/current/TopNav/Content/Aperture/t-get-new-cert-aperture-tpp.php?Highlight=nickname) and [VCert CLI](https://github.com/Venafi/vcert/blob/master/cmd/vcert/flags.go#L130).

Comment (luispresuelVenafi) [reply venafi/resource_venafi_certificate.go]: I was setting `object_name` since it seemed what most users of our provider will look into when they navigate through TPP documentation. Is there any reason why it was renamed from `object_name` to `nickname` in VCert CLI?

Comment (tr1ck3r) [reply venafi/resource_venafi_certificate.go]: Yes, it's because TPP moved away from a object/tree based user experience several years ago.  There are, of course, still certificate objects in the TPP policy tree but that detail is considered more of a "behind the scenes" or advanced usage thing.

Comment (luispresuelVenafi) [reply venafi/resource_venafi_certificate.go]: Got it, will do the renaming in the next commit.

**Review by rvelaVenafi — APPROVED** [review]

**Review by EduardoVV — APPROVED** [review]
